variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Deployment environment name"
  type        = string
  default     = "dev"
}

variable "create_rds" {
  description = "Create an RDS database for session persistence"
  type        = bool
  default     = false
}

variable "create_dynamodb" {
  description = "Create a DynamoDB table for session persistence"
  type        = bool
  default     = true
}

variable "db_engine" {
  description = "RDS database engine"
  type        = string
  default     = "postgres"
}

variable "db_instance_class" {
  description = "RDS instance class"
  type        = string
  default     = "db.t3.micro"
}

variable "db_allocated_storage" {
  description = "RDS allocated storage in GB"
  type        = number
  default     = 20
}

variable "db_name" {
  description = "RDS database name"
  type        = string
  default     = "supportassistant"
}

variable "db_username" {
  description = "RDS database username"
  type        = string
  default     = "supportadmin"
}

variable "frontend_bucket_name" {
  description = "Optional name for the frontend S3 bucket. Leave blank for autogenerated name."
  type        = string
  default     = ""
}

variable "frontend_domain_name" {
  description = "Optional custom domain name for CloudFront"
  type        = string
  default     = ""
}

variable "certificate_arn" {
  description = "Optional ACM certificate ARN for CloudFront custom domain"
  type        = string
  default     = ""
}

variable "container_cpu" {
  description = "ECS container CPU units"
  type        = number
  default     = 512
}

variable "container_memory" {
  description = "ECS container memory in MB"
  type        = number
  default     = 1024
}

variable "desired_count" {
  description = "Desired number of ECS service tasks"
  type        = number
  default     = 1
}

variable "sn_instance_url" {
  description = "ServiceNow instance URL"
  type        = string
  default     = ""
}

variable "sn_user" {
  description = "ServiceNow username"
  type        = string
  default     = ""
}

variable "sn_pass" {
  description = "ServiceNow password"
  type        = string
  default     = ""
}

variable "openai_api_key" {
  description = "OpenAI API key"
  type        = string
  default     = ""
}

variable "openai_model" {
  description = "OpenAI model to use"
  type        = string
  default     = "gpt-3.5-turbo"
}

variable "openai_api_url" {
  description = "OpenAI API endpoint URL"
  type        = string
  default     = "https://api.openai.com/v1/chat/completions"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "CIDR blocks for public subnets"
  type        = list(string)
  default     = ["10.0.1.0/24", "10.0.2.0/24"]
}

variable "private_subnet_cidrs" {
  description = "CIDR blocks for private subnets"
  type        = list(string)
  default     = ["10.0.11.0/24", "10.0.12.0/24"]
}
